name: Cargo release

on:
 release:
  types: [created]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10
  MACOSX_DEPLOYMENT_TARGET: 10.7

jobs:

  # Build sources for every OS
    cargo_build:
      name: Build release binaries
      strategy:
        fail-fast: false
        matrix:
          include:
            - target: x86_64-unknown-linux-gnu
              os: ubuntu-latest
              name: rust-template-x86_64-unknown-linux-gnu.tar.gz

            - target: x86_64-unknown-linux-musl
              os: ubuntu-latest
              name: rust-template-x86_64-unknown-linux-musl.tar.gz

            - target: i686-unknown-linux-musl
              os: ubuntu-latest
              name: rust-template-i686-unknown-linux-musl.tar.gz

            - target: aarch64-unknown-linux-musl
              os: ubuntu-latest
              name: rust-template-aarch64-unknown-linux-musl.tar.gz

            - target: arm-unknown-linux-musleabihf
              os: ubuntu-latest
              name: rust-template-arm-unknown-linux-musleabihf.tar.gz

            - target: x86_64-apple-darwin
              os: macOS-11
              name: rust-template-x86_64-apple-darwin.tar.gz

            - target: aarch64-apple-darwin
              os: macOS-11
              name: rust-template-aarch64-apple-darwin.tar.gz

            - target: x86_64-pc-windows-msvc
              os: windows-latest
              name: rust-template-x86_64-pc-windows-msvc.zip
              rustflags: -C target-feature=+crt-static

            - target: i686-pc-windows-msvc
              os: windows-latest
              name: rust-template-i686-pc-windows-msvc.zip
              rustflags: -C target-feature=+crt-static

            - target: aarch64-pc-windows-msvc
              os: windows-latest
              name: rust-template-aarch64-pc-windows-msvc.zip
              rustflags: -C target-feature=+crt-static

            - target: x86_64-unknown-freebsd
              os: ubuntu-latest
              name: rust-template-x86_64-unknown-freebsd.tar.gz

      runs-on: ${{ matrix.os }}
      continue-on-error: true
      env:
        RUSTFLAGS: ${{ matrix.rustflags || '' }}
      steps:
        - name: Setup | Checkout
          uses: actions/checkout@v4

        - name: Setup | Rust
          uses: dtolnay/rust-toolchain@master
          with:
            toolchain: nightly
            target: ${{ matrix.target }}

        - name: Setup | Install cargo-wix [Windows]
          continue-on-error: true
          # aarch64 is only supported in wix 4.0 development builds
          if: matrix.os == 'windows-latest' && matrix.target != 'aarch64-pc-windows-msvc'
          run: cargo install --version 0.3.4 cargo-wix
          env:
            # cargo-wix does not require static crt
            RUSTFLAGS: ""

        - name: Setup | Install cross [Linux]
          if: matrix.os == 'ubuntu-latest'
          uses: taiki-e/install-action@cross

        - name: Build | Build [Cargo]
          if: matrix.os != 'ubuntu-latest'
          run: cargo build --release --target ${{ matrix.target }}

        - name: Build | Build [Cross]
          if: matrix.os == 'ubuntu-latest'
          run: cross build --release --target ${{ matrix.target }}

        - name: Build | Installer [Windows]
          continue-on-error: true
          if: matrix.os == 'windows-latest' && matrix.target != 'aarch64-pc-windows-msvc'
          run: >
            cargo wix -v --no-build --nocapture -I install/windows/main.wxs
            --target ${{ matrix.target }}
            --output target/wix/rust-template-${{ matrix.target }}.msi

        - name: Post Build | Prepare artifacts [Windows]
          if: matrix.os == 'windows-latest'
          run: |
            cd target/${{ matrix.target }}/release
            7z a ../../../${{ matrix.name }} rust-template.exe
            cd -

        - name: Post Build | Prepare artifacts [-nix]
          if: matrix.os != 'windows-latest'
          run: |
            cd target/${{ matrix.target }}/release
            tar czvf ../../../${{ matrix.name }} rust-template
            cd -

        - name: Release | Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.name }}
            path: ${{ matrix.name }}

        - name: Release | Upload installer artifacts [Windows]
          continue-on-error: true
          if: matrix.os == 'windows-latest' && matrix.target != 'aarch64-pc-windows-msvc'
          uses: actions/upload-artifact@v4
          with:
            name: rust-template-${{ matrix.target }}.msi
            path: target/wix/rust-template-${{ matrix.target }}.msi


    upload_artifacts:
      name: Add Build Artifacts to Release
      needs: [cargo_build]
      runs-on: ubuntu-latest
      steps:
        - name: Setup | Artifacts
          uses: actions/download-artifact@v4
  
        - name: Setup | Checksums
          run: for file in rust-template-*/rust-template-*; do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done
  
        - name: Build | Add Artifacts to Release
          uses: softprops/action-gh-release@v1
          with:
            files: rust-template-*/rust-template-*
            tag_name: ${{ github.ref }}

    # Publish rust-template to Crates.io
    cargo_publish:
      name: Publish Cargo Package
      runs-on: ubuntu-latest
      steps:
        - name: Setup | Checkout
          uses: actions/checkout@v4

        - name: Setup | Rust
          uses: dtolnay/rust-toolchain@nightly

        - name: Build | Publish
          run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}